### PR TITLE
Make homepage carousel responsive

### LINKED ISSUE #521: Carousel needs to be made responsive
What it says on the tin. Needs to be made to work for screens under 1350px

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11308305-carousel-needs-to-be-made-responsive?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
fixes #521

### CODE REVIEW

**Comment by cassidyjames** [comment]
Copy is cut off on landscape on mobile.

**Comment by cassidyjames** [comment]
screenshot_2015-05-14-13-13-29

**Comment by cassidyjames** [comment]
Looks awesome here. :)

**Comment by cassidyjames** [comment]
Gonna look at the code. If it looks clean, I'll merge.

**Comment by cassidyjames** [comment]
Hm, I don't like the setting styles directly from the js (better to add/remove classes and set the styles in the CSS) but that's not unique to this branch. I'll open a separate issue for that.

**Comment by lewisgoddard** [comment]
I have no issue for setting calculated styles like `min-height: calculatedValue` because that can't be done in CSS.

**Pull request merged**
