### PR TITLE
Adds a sidebar to docs

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by danrabbit** [comment]
fixes #525

**Comment by lewisgoddard** [comment]
I can't seem to get the reference section to expand on `/docs/code/reference#reporting-bugs`

**Comment by lewisgoddard** [comment]
* [ ] Footer should nudge sidebar up.
* [ ] Header should be active at half page height.
* [ ] Cache sidebar links:
```
$sidebarLinks = $('.sidebar li');
$sidebarLinks.removeClass('active');
```

**Comment by emersion** [comment]
Ready to merge?

**Comment by danrabbit** [comment]
I'm happy with it :D

**Pull request merged**
