### PR TITLE
Adds prepush script for Transifex

### PR DESCRIPTION
**Pull request by emersion**
Transifex used to auto-update translation strings from the website but it's not working anymore (it's related to the .io domain). I contacted them, they said they'll fix it but I have no news anymore.

So I created a little script `.tx/prepush.sh` to extract translations from source files. It will be a lot easier to push new translations to Transifex.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
I can test this thoroughly once I have `hig-docs` ready sometime this weekend, and since I've never submitted translations before, it will be a thorough test.

**Comment by emersion** [comment]
@lewisgoddard Could you review this please? It would be easier to push HIG docs translations to Transifex with it :-P

**Comment by lewisgoddard** [comment]
@emersion I could run it without changing the first line to `#!/bin/bash`

**Comment by emersion** [comment]
Fixed !

**Pull request merged**
