### PR TITLE
All SVG has beeen optimized by SVGO

### PR DESCRIPTION
**Pull request by choyan**
Optimized all SVG images inside of images folder. Used node plugin svgo to do so. Size of all svg images has been reduced by 50-60%

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This pull request says it can't automatically be merged, so it seems you'll need to update your branch.

**Comment by choyan** [comment]
@lewisgoddard conflicts has been removed.

**Comment by lewisgoddard** [comment]
I hope to test this branch shortly.

**Comment by lewisgoddard** [comment]
`images/get-involved/translations.svg` doesn't load for me, `This page contains the following errors: error on line 1 at column 2: StartTag: invalid element name.`

**Comment by choyan** [comment]
Forgot to check myself. I hope everything is okay at the moment.

**Pull request merged**
