### PR TITLE
Add new 0$ button

### PR DESCRIPTION
**Pull request by maxrimue**
This has bothered me a bit when I downloaded elementary myself, I'm aware that you can click custom and then just type "0", but it might seem confusing for some other people. I think the goal of elementary is to be attractive to all kinds of users, and some might think that you have to donate for downloading elementary.
Also, I don't think this change would have an impact on how many people donate, as they should do it only if they want anyway.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Seeing as less than half of our downloads come through the site anyway, and more than 99% are currently not paying on the site, I don't think this is as confusing as you think. If more than 99% of people understand how to do it, then that's actually some pretty damn good UI. On the other hand, this change of actively _not_ contributing, rather than having the default of nothing, has nearly doubled the amount of people paying for their download, which has further has enabled elementary to place over $15,000 on bug bounties, a vast majority of which has been claimed already.

The design decisions behinds this have been previously explained in the blog post [Payments (Or, Why we make you type “$0”)](http://blog.elementary.io/post/110645528530/payments), with a follow-up post on our spending detailed in a [thank you](http://blog.elementary.io/post/118806943356/thank-you-everyone) post.

**Comment by lewisgoddard** [comment]
Functionally, the code is sound. It will add a `$ 0` button to the left of existing buttons, keeping the left-to-right increment, with correct styles and logic applied. The `$ 10` button will remain the default selection.

I am going to mark this as "Needs Design" since that is not my area to make a final decision in.

**Comment by maxrimue** [comment]
@lewisgoddard 99% of the people downloading it are not paying, this doesn't mean that everyone who wants to download it really does it after all.
Having read the post you linked, I can only agree that probably more people donate when you make it easier to donate, or highlight the option of donating. However, only those people who want to donate will donate anyway, others will type "0" or leave, and since this PR doesn't remove these buttons with pre-defined values, I don't think this has any impact on the donations.

**Comment by lewisgoddard** [comment]
As I said, final decision will go to the design team. Here's a screenshot for reference on how the page looks on load.
screenshot from 2015-05-13 12 32 45

**Comment by maxrimue** [comment]
@lewisgoddard Thanks

**Comment by KeitIG** [comment]
Well, I agree if the 10$ button is selected by default.

But of course, all the debate is about "should the user write '0' to download Freya for free ?". There was long discussions about that.

**Comment by maxrimue** [comment]
@KeitIG Well, I wouldn't remove the other buttons and such as well, I get the reason why it is how it is now, but adding the 0$ button, while not removing another button nor setting another one as the new default, I guess it wouldn't change the behaviour of the users that want to download elementary. Instead, seeing it's okay if you click "0$" might get more people to download it, as I said, there are maybe some that aren't downloading it because of the missing option of 0$.

I'd actually be interested in some stats on how many people click the download button with the 10$ selected, but then leave the site without downloading.

**Comment by lewisgoddard** [comment]
@maxrimue Unfortunately, we're not currently collecting stats on how many people click the download button, nor whether or not they exit.

**Comment by cassidyjames** [comment]
We've had lengthy discussions about this topic. In the post Lewis linked, we explicitly explain why we moved to a model of typing $0, and that still applies.

**Comment by lewisgoddard** [comment]
#634 is an issue about this with some discussion from our design lead, @danrabbit, in addition to the following posts:
http://blog.elementary.io/post/110645528530/payments
http://blog.elementary.io/post/118806943356/thank-you-everyone

**Pull request closed without merging**
