### PR TITLE
Support

### LINKED ISSUE #264: Support landing page [$50]
We need a Support page that tells users where they can go to have their support questions answered.

Ideally this includes links to documentation and communities.

<bountysource-plugin>

---
There is a **[<total-bounty>$50</total-bounty> open bounty](https://www.bountysource.com/issues/8114203-support-landing-page?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
Creating a pull request so we can track feedback/todos for this branch outside of the bug report

Fixes #264

### CODE REVIEW

**Comment by danrabbit** [comment]
* Thoughts on using the actual Reddit and Google+ full logos instead of an icon and text?
* I think the "Get support for a specific app" and the hr are unnecessary. I think it's clear from the context here what the icons are about.
* Maybe we should have the FAQ link [here](https://answers.launchpad.net/elementary/+faqs) since we don't currently have a URL for that.
* Not sure I like the text beside icons. The big bar sticking out the side is weird to me and the whole grid is aligned left on the page instead of centered. Why not labels centered beneath icons?

**Comment by cassidyjames** [comment]
@danrabbit 

* Reddit/G+ Logos: hm, like just use big icons to the left of the paragraphs?
* heading/hr: I'll see how it looks without
* FAQ link: Good call
* Icons: I was going for that welcome-screen sorta look, but yeah I'll see what it looks like with the text under the icons. More like Switchboard.

**Comment by lewisgoddard** [comment]
This branch can now be viewed here: http://beta.elementary.io/branch/support/support

**Comment by lewisgoddard** [comment]
I personally think the `hr` needs toning down a lot, something like `#ccc` as the center color, not 75% black. 

screenshot from 2015-02-18 20 08 03

**Comment by emersion** [comment]
Looks very good :-D

Just one thing on mobile: the navbar bug triggers a heading bug:

selection_519

Maybe adding a `clear: both` can solve this problem?

**Pull request merged**
