### PR TITLE
Fix #1276: Move icons to a git submodule

### LINKED ISSUE #1276: Use git submodules for icon theme
We should be using a git submodule to keep our copy of the icon set up to date. This will also remove the mess that is the mvp icon directory.

### PR DESCRIPTION
**Pull request by lewisgoddard**
Fixes #1276

### Changes Summary

- [x] Remove `images/icons`
- [x] Add `git submodule`
- [x] Fix links
  - [x] Midori on Privacy Policy
  - [x] Slingshot
- [x] Remove Duplicates
- [x] Add to build.

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
- Slingshot images
- Slider switch icons

**Comment by lewisgoddard** [comment]
@danrabbit Not yet, added to list.

**Comment by lewisgoddard** [comment]
- [ ] Midori on Privacy Policy
- [ ] Slingshot

**Comment by danrabbit** [comment]
As far as I can tell, there's nothing broken and the icons install transparently when npm install is run. Works for me :+1:

**Comment by lewisgoddard** [comment]
@btkostner Are you okay for me to merge this? It will break the `loki` branch again.

**Pull request merged**
