### PR TITLE
Add manifest for Android homescreen title; fixes #102

### LINKED ISSUE #102: Set smarter mobile web app title
I don't think this is a good page title. Especially if we consider that this site will eventually host documentation and other links and not just the Freya download.

Mainly, where I'm experiencing this problem is with bookmarking this site. Especially using the "add to homescreen" function on my mobile. Having a homescreen icon with "elementary OS Freya" is weird.

I think simply "elementary" would be the most encompassing

### PR DESCRIPTION
**Pull request by cassidyjames**
per https://developer.chrome.com/multidevice/android/installtohomescreen

### CODE REVIEW

**Comment by danrabbit** [comment]
I think this should go in here? I'm not 100% sure it's right. Lemme know if it looks odd.

**Comment by cassidyjames** [comment]
@danrabbit gonna check here shortly. :)

**Comment by danrabbit** [comment]
Made some alterations based on our discussion and here's sizes

**Comment by danrabbit** [comment]
Let's just scaled the 192 one because the material design guidelines are BS and the phone is grabbing the wrong size

**Comment by cassidyjames** [comment]
Ha aight, updating...

**Comment by cassidyjames** [comment]
@danrabbit looks aight to me.

**Comment by cassidyjames** [comment]
This branch will also fix #225

**Pull request merged**
