### PR TITLE
Docs by MDR (Closes #331)

### LINKED ISSUE #331: Port the User Guide
We should port the user guide over from http://elementaryos.org/docs/user-guide/user-guide to the new site. I think more of a single-page guide with collapsible sections might work better than maintaining multiple individual pages, but I'm up for discussion.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8187597-port-the-user-guide?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lewisgoddard**
* Add MDR
* Add Markdown support to translations
* Refactor [installation](https://beta.elementary.io/branch/docs-by-mdr/docs/installation) page to [markdown document](https://beta.elementary.io/branch/docs-by-mdr/docs/installation.md)
* Add [Learning the Basics](https://beta.elementary.io/branch/docs-by-mdr/docs/learning-the-basics) document, closing #331
* Add some server configuration

I think we are better merging this now rather than wait for the other documents.
Those could take some time, and will just lead to a bigger diff in the future.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
@emersion I'm not a fan of your "cleanup" of MDR. It's bad practice to put comments on the same line of code and I like knowing what brackets close what. I've also removed the l10n inclusion seeing as it's pulled in with the header already.

**Comment by emersion** [comment]
Okay, do what you want, I though this wasn't intentional ;-) everyone has its own vision of beautiful code

**Comment by lewisgoddard** [comment]
If someone can fix the conflicts I am okay with this being merged.

**Comment by emersion** [comment]
Let's do this

**Pull request merged**
