### PR TITLE
1049 menu overlap ios

### PR DESCRIPTION
**Pull request by Lukewh**
https://github.com/elementary/mvp/issues/1049

### CODE REVIEW

**Comment by lewisgoddard** [comment]
ok to test

**Comment by lewisgoddard** [comment]
I really hope I can find someone to test this.

**Comment by btkostner** [comment]
Looks correct in iOS 9.2.1

**Comment by cassidyjames** [comment]
@rabbitbot ok to test

**Comment by lewisgoddard** [comment]
I'm happy to leave this open if we still want rabbitbot to test it, but since it's just CSS I'm happy if it works.

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
test this please

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
retest this please

**Comment by fabianthoma** [comment]
retest this please

**Comment by fabianthoma** [comment]
retest this please

**Comment by fabianthoma** [comment]
retest this please

**Comment by fabianthoma** [comment]
Sorry if I spammed your inboxes or github feed, but finally the pull request builds should be back for external PRs

**Pull request merged**
