### PR TITLE
Fix #969: min-width for container and center align doughnuts

### LINKED ISSUE #969: The Burndown Chart Moves Horizontally on Mouse-Over
I'm viewing the site on Chrome in Windows 7, and the burndown chart moves horizontally when the width of the date gets too big. Everything seems fine in the early months until you go from August to September. Let me know if you need more clarification.

### PR DESCRIPTION
**Pull request by Lukewh**
Fix for long dates making the disco-dom

https://github.com/elementary/mvp/issues/969

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This branch was forked and merged in #997

**Comment by Lukewh** [comment]
@lewisgoddard I don't understand what you mean by this branch being forked and merged in #997? Have my changes been merged?

**Comment by lewisgoddard** [comment]
Yes, if you take a look there the changes are nearly identical.

**Comment by Lukewh** [comment]
Hmm, not sure about removing the left hand margin as it doesn't let the graph breath or use the width available at larger sizes.

**Pull request closed without merging**
