### PR TITLE
Adds merge script for Transifex

### PR DESCRIPTION
**Pull request by emersion**
- Adds merge script which has been used to migrate translations after #582.
- Fixes an issue with extract-l10n: wrong `$sitewide['root']` value

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Can you provide some instruction for testing this?

**Comment by emersion** [comment]
Done! ;-)

**Comment by emersion** [comment]
For reference, here is the command used to merge HIG docs translations:
```bash
php .tx/merge.php -o docs/human-interface-guidelines docs/human-interface-guidelines/actions docs/human-interface-guidelines/always-provide-an-undo docs/human-interface-guidelines/always-saved docs/human-interface-guidelines/app-launchers docs/human-interface-guidelines/appmenu docs/human-interface-guidelines/avoid-configuration docs/human-interface-guidelines/background-tasks docs/human-interface-guidelines/buttons docs/human-interface-guidelines/capitalization docs/human-interface-guidelines/checkboxes-switches docs/human-interface-guidelines/closing docs/human-interface-guidelines/concision docs/human-interface-guidelines/contractor docs/human-interface-guidelines/design-philosophy docs/human-interface-guidelines/desktop-integration docs/human-interface-guidelines/dialogs docs/human-interface-guidelines/dock-integration docs/human-interface-guidelines/first-launch-experience docs/human-interface-guidelines/human-interface-guidelines docs/human-interface-guidelines/icons docs/human-interface-guidelines/infobars docs/human-interface-guidelines/language docs/human-interface-guidelines/launcher-icons docs/human-interface-guidelines/mimetypes docs/human-interface-guidelines/minimal-documentation docs/human-interface-guidelines/naming-menu-items docs/human-interface-guidelines/normal-launch docs/human-interface-guidelines/notebooks docs/human-interface-guidelines/popovers docs/human-interface-guidelines/punctuation docs/human-interface-guidelines/search-fields docs/human-interface-guidelines/size-and-alignment docs/human-interface-guidelines/sizes docs/human-interface-guidelines/source-list docs/human-interface-guidelines/style docs/human-interface-guidelines/symbolic docs/human-interface-guidelines/system-indicators docs/human-interface-guidelines/text docs/human-interface-guidelines/toolbars docs/human-interface-guidelines/ui-toolkit-elements docs/human-interface-guidelines/user-workflow docs/human-interface-guidelines/using-ellipses docs/human-interface-guidelines/welcome-screen docs/human-interface-guidelines/what-design-is-not docs/human-interface-guidelines/widget-concepts docs/human-interface-guidelines/window-titles docs/human-interface-guidelines/windows docs/human-interface-guidelines/writing-style
```

**Comment by lewisgoddard** [comment]
I get a load of warnings like `No file found for resource docs/human-interface-guidelines in language eu_ES`. I am assuming these  are warnings where we haven't translated yet, and not errors.

**Comment by lewisgoddard** [comment]
It appears to work however, so I'm approving.

**Comment by lewisgoddard** [comment]
Or at least I would If that button were "Comment & Merge".

**Pull request merged**
