### PR TITLE
Add HIG Docs

### PR DESCRIPTION
**Pull request by lewisgoddard**
http://beta.elementary.io/branch/hig-docs/docs/human-interface-guidelines/human-interface-guidelines

* Add page title.
* Add IDs to all non-repeated headers.
* Move all images to `/images/docs/human-interface-guidelines`
* Add next links.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Still only 27/48.

**Comment by seanballais** [comment]
Make that 28/48. I worked one already.

**Comment by lewisgoddard** [comment]
@seanballais Sorry, I didn't see your branch until just now.

I would have still needed to make changes since the `/uploads` folder hadn't been moved over, but thank you for trying to help.

**Comment by seanballais** [comment]
Oh, it's fine. Is there something else I could work on? Preferably a medium scale task.

**Comment by lewisgoddard** [comment]
@seanballais There's 3 bitesize issues that should be easy enough to start off, and pretty much anything labelled as confirmed, but not wishlist or in progress is the priority.

**Comment by danrabbit** [comment]
- [ ] All reference articles should open in a new tab
- [ ] Links to other sections in body copy seem to not work

**Comment by lewisgoddard** [comment]
@danrabbit Done and done.

**Pull request merged**
