### PR TITLE
Remove amount selection after payment, fixing #339

### PR DESCRIPTION
**Pull request by devTristan**
This should fix it. Could use a review. Hope the style is okay.

All I did in index.php was add `<div class="amounts"> ... </div>` plus an indentation, hence the unnecessarily long diff.

I'm fairly sure it'll work in theory, but I don't have a spare stripe API key sitting around.

Relevant: Would it be possible/safe to put a stripe test key in this repo?

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This needs master merged or rebased before I can test it.

**Comment by devTristan** [comment]
you got it, looking at this now

**Comment by devTristan** [comment]
Okay, that should do it, I think.

**Comment by devTristan** [comment]
Thanks @lewisgoddard :)

**Pull request merged**
