### PR TITLE
Maybe fix #544

### LINKED ISSUE #544: Open Sans Local on Windows lacks some character sets.
Opens sans fonts used on homepage don't contain some characters, so Arial gets used instead. And it looks like Google webfonts version has the possibility to include those character sets. Windows 8.1, Firefox 37.0.1

Example:
font_bug

### PR DESCRIPTION
**Pull request by lewisgoddard**
Maybe fix #544

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Huh, I have no idea how to test this in Windows without enabling languages on that branch.

**Comment by KeitIG** [comment]
Test site return a 403 error.

**Comment by lewisgoddard** [comment]
Huh, no idea why, apart from the fact our test site can't test translated versions.

**Comment by emersion** [comment]
You can specify the `lang` parameter instead: https://beta.elementary.io/branch/origin/possibly-544/?lang=pl

**Comment by lewisgoddard** [comment]
It totally works!

screenshot from 2016-01-05 21 59 06

**Pull request merged**
