### PR TITLE
Adding vagrant environment

### PR DESCRIPTION
**Pull request by javaguirre**
Hi!

I've just created a simple [Vagrant](https://www.vagrantup.com/) environment to isolate the development of the project. I selected the `ubuntu\trusty64` box for It, but we should change It to the correct production server OS (I don't know which is It).

Thank you!

### CODE REVIEW

**Comment by lewisgoddard** [comment]
What version of PHP does this run with?

**Comment by javaguirre** [comment]
The same as in the Elementary production server.

screenshot from 2015-06-21 16 52 35

In the vagrant machine:

screenshot from 2015-06-21 16 54 27

**Comment by lewisgoddard** [comment]
I guess that's for the best. Ideally, I'd like both upgraded to 5.6, but I think that's a separate bug.

**Comment by javaguirre** [comment]
I agree with you.

**Pull request merged**
