### PR TITLE
Change <button> to <a> for downloads

### LINKED ISSUE #2: Get a site favicon
Gotta have one of those

### PR DESCRIPTION
**Pull request by KeitIG**
It was a really strange issue: while the whole document was supposed to be in open-sans, and buttons were in Helvetica, they randomly were caming back to font-size: medium and font-family: "open-sans". It may be a chrome issue.

I specified font-size and font-family for buttons, and made the download button an <a> tag for better semantic and to avoid strange onClick.

### CODE REVIEW

**Comment by danrabbit** [comment]
Hm this branch introduces a change that causes the button to go into two lines on mobile (specifically at 320 x 568)

**Comment by KeitIG** [comment]
I specified `Helvetica` because of `font-family: "body { font-family: Open Sans", "Droid Sans", Helvetica, sans-serif; }`, and Open sans does not look so great for this button

**Comment by danrabbit** [comment]
This branch can't be merged into trunk. Please fix merge conflicts.

As I believe #15 should be fixed already, I'm assuming the purpose of the branch is to change the button to an anchor

**Comment by KeitIG** [comment]
I merged master to this branch to resolve conflicts

**Comment by danrabbit** [comment]
It looks like this is still unable to be automatically merged into master

**Comment by KeitIG** [comment]
I merge from master, then merge to master now it's reviewed

**Pull request closed without merging**
