### PR TITLE
Adds smooth scrolling

### LINKED ISSUE #209: Add smooth scroll-to
on get involved it would be nice if we smoothly scrolled to each section

### PR DESCRIPTION
**Pull request by emersion**
Fixes #209 and #231

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Would we not want this on every page, seeing as it's such a small snippet and we would want _any_ id to be scrolled to, not jumped to.

**Comment by emersion** [comment]
Moved jQl and scmooth scrolling to `header.js`.

**Comment by cassidyjames** [comment]
I'm not getting smooth scrolling in either Chrome or Firefox. :worried:

**Comment by lewisgoddard** [comment]
@cassidyjames Really? I do on this page http://beta.elementaryos.org/get-involved Click any of the four buttons near the top.

**Comment by emersion** [comment]
@cassidyjames You may have to clear your cache (or pressing `F5`+`F5`+`F5`+`F5` ;-) )

**Comment by lewisgoddard** [comment]
Oh, and you have to wait until the page has finished loading.

**Comment by cassidyjames** [comment]
Yeah I might've also had it cached or something. :)

**Pull request merged**
