### PR TITLE
Add legacy browser warning, fixes #32

### LINKED ISSUE #32: Warn users of outdated browsers
While not many of our visitors use outdated browsers, we should warn those who do that their browser is outdated and that our site won't work properly.

On system76.com we simply throw a big ol' header on <=IE10 with a link to browsehappy.com

```
<!--[if lt IE 10]>
	<div id="legacy-warning">
		<h1>System76 is built on modern web technologies your browser doesn&rsquo;t support.</h1>
		<p>This version of Internet Explorer is out of date and may contain bugs or security vulnerabilities. Please <a href="http://browsehappy.com/">upgrade</a> to IE 11 or an alternative web browser.</p>
		<p>If you have questions about an order or require support, feel free to <a href="/contact">contact us</a>.</p>
		<div id="legacy-warning-buttons">
			<a href="#" onClick="document.getElementById('legacy-warning').style.display = 'none';">Dismiss</a>
			<a class="primary" href="http://browsehappy.com/">Learn More</a>
		</div>
	</div>
<![endif]-->
```

This is then styled up with CSS and works quite well. I'm open to discussion on how else to implement it, but no matter what let's keep it simple. :)

### PR DESCRIPTION
**Pull request by cassidyjames**
Simple, similar to what we did on System76's site.

### CODE REVIEW

**Comment by KeitIG** [comment]
Well, IE10 ?

IE9 supports most of the HTML5 and CSS3 features, we can support it and diaplay this message for IE<=8.

**Comment by lewisgoddard** [comment]
`{` should have a preceding space.

**Comment by cassidyjames** [comment]
@KeitIG good call I'll update it.

@lewisgoddard ah I didn't realize that was our style. Update incoming.

**Comment by lewisgoddard** [comment]
Oh, I think you had two `<` before the closing tag. Didn't notice, my bad.

**Comment by lewisgoddard** [comment]
Or is that how IE tags look? Damnit, closed my VM.

**Comment by cassidyjames** [comment]
@lewisgoddard naw you're right, fixing.

**Pull request merged**
