### PR TITLE
Fix 404 Errors (Fixes #646)

### LINKED ISSUE #646: Redirect old answers and journal folders.
In the Nginx config, we need to redirect `/journal*` to blog.elementary.io and `/answers*` to `/support`, so that urls like `/journal/luna-beta-1-released` and `/answers/missing-dropbox-indicator` get shown a more informative page. That's almost 90% of all 404 errors.

Note: Trailing slashes are important, they stop `/support` ending in  a redirection loop, but still fix things like `/support/answers/3366`.

### Nginx Redirects (for catch-alls)
- [ ] `/journal*` to `http://blog.elementary.io/` (replaces file)
- [ ] `/answers*` to `/support` (replaces file)
- [ ] `/user-guide*` to `/docs/learning-the-basics`
- [ ] `/docs/human-interface-guidelines/*` to `/docs/human-interface-guidelines`
- [ ] `/download*` to `/`
- [ ] `/payment*` to `/`
- [ ] `/support/*` to `/support`

### File Redirects (for individual pages)
Only existing ones.

### To Sort
- [ ] `/search*`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14479885-redirect-old-answers-and-journal-folders?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lewisgoddard**
- Fixes #646
- Will stop around 250 file not found errors per day by sending them some place relevent.
- This requires server-side modification.

### To Do
- [x] Figure out where to send `/search*`
- [x] Add documentation on loading configuration.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Search can 404, nothing like that exists anymore, and there's only a few dozen requests.

**Comment by lewisgoddard** [comment]
Okay, it's up for review, but I need someone with server-side access to merge this so changes can be made. We could even follow the new instructions in `CONTRIBUTE.md`, but we'd need to add in keys and hashes for SSL.

**Comment by fabianthoma** [comment]
I applied the config on the server as well, should all be done

**Comment by lewisgoddard** [comment]
Confirmed, `/answers/12345` now goes to `/support`

**Pull request merged**
