### PR TITLE
fix 813

### PR DESCRIPTION
**Pull request by btkostner**
what the title says

### CODE REVIEW

**Comment by btkostner** [comment]
fixes #813

**Comment by lewisgoddard** [comment]
You should be able to move that outside the switching div so that it isn't replicated 3 times over.

**Comment by lewisgoddard** [comment]
The side affect of that may be that it is statically below the length of the longest content, not the selected one. That, however, is an existing bug in the Slider.

**Comment by btkostner** [comment]
It does some weird flow issues with the slider too
overflow

**Comment by btkostner** [comment]
updated. should work after #868

**Pull request merged**
