### PR TITLE
Hash update

### PR DESCRIPTION
**Pull request by btkostner**
added hash updating url and sidebar navigation to the docs

### CODE REVIEW

**Comment by btkostner** [comment]
fixes bug #595

**Comment by lewisgoddard** [comment]
This is going to require some serious testing, and I think emersion wrote most of that code.

**Comment by emersion** [comment]
Okay, will review.

**Comment by lewisgoddard** [comment]
I've only got a couple of minor problems, mostly the issues it exposes with our consistency, or rather lack of consistency. `/docs/installation` only has 1 header that is detected, since the rest were not properly formatted.

**Comment by lewisgoddard** [comment]
Since I can't edit your repository, I've proposed a branch at #706 that fixes the issues with `/docs/installation`

If you are happy with those modifications and merge them here, I will merge this branch (unless someone else merges mine to master first, although we seem to be slacking with that).

**Pull request merged**
