### PR TITLE
Fixes the 404 page bug

### PR DESCRIPTION
**Pull request by emersion**
How to reproduce:

1. Go to the main page
2. Change language
3. Append random chars to the URL
4. White 404 page

### CODE REVIEW

**Comment by emersion** [comment]
Seems a problem with nginx config, the 404 page isn't even executed. See http://beta.elementary.io/branch/fix-404/?lang=fr (we can see that `_templates/` files are included) and http://beta.elementary.io/branch/fix-404/fdsafdsa?lang=fr (still white, should print at least _404 included_).

**Comment by emersion** [comment]
One possibility: it loads the 404 page from the root and not from my branch so I'm not able to debug.

**Comment by lewisgoddard** [comment]
Yeah, it will be loading the 404 page from root. You'll need to get @fabianthoma to update the config just for your branch.

**Comment by emersion** [comment]
Okay, will setup nginx locally too. :-P

**Comment by lewisgoddard** [comment]
@emersion Is this good to review then? Labels suggest not.

**Comment by emersion** [comment]
No, I have to test locally the nginx config and see why it's not working, since there is no problem with the php dev server.

**Comment by lewisgoddard** [comment]
The test URLs seem to have been completed by subsequent work, probably in #683

**Pull request closed without merging**
