### PR TITLE
Adds /capnet-assist

### LINKED ISSUE #814: Create a landing page for Capnet Assist [$25]
Right now it's just pointing to our home page which looks like an ad. We should make a simple "error" page it can point to that explains why this window has appeared/what capnet is/we messed up somewhere

Ideally, users should never see this, but for some reason they are.

--

[Bounty on Bountysource](https://www.bountysource.com/issues/26103693-create-a-landing-page-for-capnet-assist)

### PR DESCRIPTION
**Pull request by emersion**
Fixes #814 

I decided to hide header & footer with css rules to avoid hardcoding css styles, analytics, base html layout in `/capnet-assist.php`.

See https://beta.elementary.io/branch/origin/capnet-assist/capnet-assist

### CODE REVIEW

**Comment by lewisgoddard** [comment]
We might want a "close window" button.

**Comment by danrabbit** [comment]
The window does have its own window controls so that is probably not necessary

**Comment by lewisgoddard** [comment]
As far as I'm concerned, this is a design confirm. It's a little heavier than a static page would have been, loads the nav and footer but hides them, but at least it will keep in line with styles.

**Comment by danrabbit** [comment]
Seems fine to me :) We can always come back and make it smaller if we need to

**Pull request merged**
