### PR TITLE
Fix unresponsive web browser box. Fixes #363.

### LINKED ISSUE #363: Break the web browser image in get involved into sprites/slices
In translations, you can have an issue where the buttons are pushed over the image. We should have this background made in such a way that it can expand or contract to accommodate the size of the paragraph.

See: http://beta.elementaryos.org/fr/get-involved#web-development

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8398902-break-the-web-browser-image-in-get-involved-into-sprites-slices?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ssddanbrown**
On the get involved page regarding the web development section, Replaces the border with css and scales the svg when resizing the window. This allows the height of the box to be responsive to the varied amount of text per language. I also neatened the spacing of the 'browser window' box.

Here a screenshot of the FR page fixed, which was previously overflowing the window:

image

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for contributing :-)

Good work, but there is one issue: it looks bad on mobile/tablet.

screen shot 2015-04-12 at 11 33 12

You can see how it looks like on the current website.

**Comment by ssddanbrown** [comment]
@emersion Thanks for the feedback, I've now added an alternate toolbar image for mobiles and improved spacing/alignment.
Here is an image of how it now looks:

image

**Comment by Scribblex** [comment]
It seems to me, css is fine.

**Comment by emersion** [comment]
LGTM, thanks!

**Pull request merged**
