### PR TITLE
consistent css whitespace

### LINKED ISSUE #658: Inconsistent single property css
main.css:

200: .text-left { text-align: left; }

443: .warning {
444:    color: #fbc02d;
445: }

simple fix

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14699350-inconsistent-single-property-css?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by btkostner**
cleans up css. fixes #658

### CODE REVIEW

**Comment by lewisgoddard** [comment]
I think we probably want the whitespace after media queries, apart from that I'm okay with it.

**Comment by btkostner** [comment]
something like this instead?
```
@media (max-width: 1176px) {
  
    .dev-section {
```

**Comment by lewisgoddard** [comment]
Yes, like that.

**Comment by btkostner** [comment]
media white space is fixed in latest push

**Comment by lewisgoddard** [comment]
Unfortunately it looks like you need to rebase on master for this to be mergeable, but I might try and do that later (assuming that's not a major issue).

**Comment by lewisgoddard** [comment]
I've created a new request at #689 as a rebase of this.

**Pull request merged**
