### PR TITLE
"Mac OS X" becomes "OS X"

### PR DESCRIPTION
**Pull request by maliktunga**
According to Wikipedia, "Mac OS X" is a former name: https://en.wikipedia.org/wiki/OS_X

Again, I don't know if I should update the HTML alts and hrefs. Even images are named "macos", which is an obsolete name.

### CODE REVIEW

**Comment by danrabbit** [comment]
Yes, if it's not too inconvenient, please change the image names, hrefs, etc

**Comment by maliktunga** [comment]
To avoid breaking things,

> mvp/images/installation/macos_dialog.png

should be renamed

> mvp/images/installation/osx_dialog.png

Also,

>  mvp/images/installation/macos_menu.png

should be renamed

> mvp/images/installation/osx_menu.png

**Comment by danrabbit** [comment]
Yes please do that in this branch

**Comment by maliktunga** [comment]
@danrabbit How can I do that?

**Comment by danrabbit** [comment]
git mv oldfilename newfilename

**Comment by maliktunga** [comment]
@danrabbit Hmm, I used Nautilus instead ;-P

(I'm a crappy developer haha)

Alright, so first time using "git clone" with a branch. I think it worked. Please check everything I did in this pull request! Here might be dragons.

**Comment by maliktunga** [comment]
@danrabbit I think this pull request does not need the "Needs Fixing" label anymore.

**Comment by danrabbit** [comment]
Looks good, nothing broken here. Good job :)

**Comment by maliktunga** [comment]
@danrabbit Great thanks!

**Pull request merged**
