### PR TITLE
Added a simple Square store page

### PR DESCRIPTION
**Pull request by maffity**
@cassidyjames helped me set up git and create a branch. :smile:

### CODE REVIEW

**Comment by maffity** [comment]
Fixes #274

**Comment by danrabbit** [comment]
- [ ] That's pretty legit. I wonder if we should remove the border?
- [ ] I feel like this needs a link in header.php
- [ ] Clicking checkout takes me to square's website. Is there any way to do this in a new page so we don't navigate away with no way to get back?

**Comment by maffity** [comment]
The border is added automatically by Square, but we might be able to style it with CSS.

**Comment by maffity** [comment]
Oh, it was a setting in the embed code. Removed!

**Pull request merged**
