### PR TITLE
Make slider.js use more CSS and less JS

### LINKED ISSUE #663: Refactor slider to use less js, more CSS
The homepage slider right now is doing several things in js that could be done with CSS. This could potentially also fix #651.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14890076-refactor-slider-to-use-less-js-more-css?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
fixes #663 #651 

- [x] fix the way container height is calculated
- [x] set "next" and "previous" classes before running slideTo so that setting slide with OS detection works

### CODE REVIEW

**Comment by lewisgoddard** [comment]
I am almost done with a re-write of `slider.js`. Am I okay to push to this branch?

**Comment by danrabbit** [comment]
Hm there's something funky going on. On Safari mobile when I click a pager button it flashes a bit and there's no sliding animation.

**Comment by danrabbit** [comment]
We need to run transforms through a prefixer http://pleeease.io/play/

**Comment by danrabbit** [comment]
Okay fixed. The flashing seems to be a button active effect that's baked into Safari. But transforms are working now.

**Comment by lewisgoddard** [comment]
I approve this code for Chrome, Firefox and Midori in Freya.

**Comment by danrabbit** [comment]
And I can confirm Lewis' Jquery changes work in Mobile Safari, Chrome, and Midori

**Pull request merged**
