### PR TITLE
flex nav

### PR DESCRIPTION
**Pull request by btkostner**
We can clean up the header and remove breakpoints by using flexbox.

caniuse.com put unprefixed flexbox support at 72.42% of browser usage. (http://caniuse.com/#feat=flexbox)

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes

Here is an image of it in firefox 7.0.1 on Windows XP.
xp

### CODE REVIEW

**Comment by btkostner** [comment]
this will fix #619 and all other nav bar overflow related issues

**Comment by lewisgoddard** [comment]
Needs re-basing and IE 8 fallback, as discussed.

**Comment by btkostner** [comment]
No ie8 support, but ie9 works great. Also removed double scroll bar thing.

nav

**Comment by lewisgoddard** [comment]
This looks good, I'm just waiting on @fabianthoma fixing our build checker.

**Comment by fabianthoma** [comment]
ok to build

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
@rabbitbot test this please

**Comment by fabianthoma** [comment]
retest this please

**Pull request merged**
