### PR TITLE
Stripe Email Receipts

### PR DESCRIPTION
**Pull request by lewisgoddard**
**Pass using proper variable names, add config for testing branches too.**

Unlike funnylookinhat's branch, this encodes the email for submission and fixes a related cookie issue.

_This is a new branch because my previous branch had fallen too far out of sync with master, and I the rebase was very messy._

**Testable at http://beta.elementary.io/branch/stripe-receipts-3**

### Proof
screenshot from 2015-04-01 14 48 38

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This would fix #340

**Comment by lewisgoddard** [comment]
Added a condition so the branch still works while being mergable to master.

**Comment by bradaric** [comment]
Glad to finally hear that my encodeURIComponent() call did the trick :) Keep up the speedy work ;)

**Comment by emersion** [comment]
Can't test by myself, but seems that it's working on the screenshot.

**Pull request merged**
