### PR TITLE
Redesigned the sidebar

### PR DESCRIPTION
**Pull request by seanballais**
I redesigned the sidebar with a flat/material design one to complement the website. Also fixed the 'Doc' bug that appears in every `<ul>`.

### CODE REVIEW

**Comment by emersion** [comment]
* Not working 
screen shot 2015-04-24 at 16 41 41
* That's not what we want. Docs indexes are not sidebars!

**Comment by seanballais** [comment]
Sorry, my bad.

**Comment by lewisgoddard** [comment]
We do want that design but I think we want it to just have links to each section header on the current page. Searching for something like `.docs h#` should do it.

**Comment by danrabbit** [comment]
Closing this since it's been solved in #588 (Sorry!)

**Comment by seanballais** [comment]
It's okay. It's for the good of the website anyway. :+1: :)

**Pull request closed without merging**
