### PR TITLE
Added link to Wikipedia page #334

### PR DESCRIPTION
**Pull request by nblackburn**
See #334

### CODE REVIEW

**Comment by cassidyjames** [comment]
Oh the book icon is an interesting idea. In case anyone is wondering, here's what it looks like in context.

screenshot from 2015-02-07 20 29 58

**Comment by danrabbit** [comment]
Hrm I dunno about the book. At first glance it looks like "documentation" or something. I think we should still use the wiki "w"

**Comment by snwh** [comment]
I agree with Dan, the logo would be more recognizable. 

However, is there any need to link to the wikipedia page?

**Comment by fabianthoma** [comment]
First I also think the iconic W of Wikipedia should be used, but I have to agree with @snwh here, does one need/should link to wikipedia? It's a place for knowledge, and if anything that knowledge should also be represented on our own website.

**Comment by nblackburn** [comment]
The "W" icon would be more relevant but FontAwesome doesn't contain that icon so made do with the resources available.

**Comment by KeitIG** [comment]
as Cassidy posted here, this icon may be on the road https://github.com/FortAwesome/Font-Awesome/issues/388

**Comment by shoully** [comment]
Yeap, it's on Font-Awesome 5.0.0 milestone.

**Comment by emersion** [comment]
See #334.

**Comment by nblackburn** [comment]
The [Wikipedia](http://fontawesome.io/icon/wikipedia-w) icon has arrived.

**Pull request closed without merging**
