### PR TITLE
Update purple to match Valadoc

### PR DESCRIPTION
**Pull request by cassidyjames**
will need to do the CSS and meta theme-colors

### CODE REVIEW

**Comment by cassidyjames** [comment]
will fix #1025

**Comment by cassidyjames** [comment]
@snwh doesn't like the purple. I leave it to @danrabbit to decide the fate of this PR.

**Comment by snwh** [comment]
@snwh is indifferent

**Comment by lewisgoddard** [comment]
Can I merge this, or do I need #ux ?

**Pull request merged**
