### PR TITLE
Fix Getting Started docs page

### PR DESCRIPTION
**Pull request by inad9300**
Fixes #

### Changes Summary

- Change link wrongly pointing to the Getting Started page of the docs (md extension was missing)
- Same case for a link (wrongly) pointing to the Human Interface Guidelines
- Add -C option to the ssh-keygen command example -- Launchpad requires it to be present
- Fix CMakeList.txt file with solution suggested in https://bugs.launchpad.net/writer/+bug/1357072/comments/6
- Fix small typos

This pull request is ready for review.

### CODE REVIEW

**Comment by btkostner** [comment]
The links you fixed should not include the `.md` file extension, otherwise they will link to the raw markdown file.

https://elementary.io/docs/human-interface-guidelines.md
https://elementary.io/docs/human-interface-guidelines

**Comment by inad9300** [comment]
Just give it a try and click them. They are relative links to GitHub's documents, not elementary's. Once they are resolved, we have https://github.com/elementary/mvp/blob/master/docs/human-interface-guidelines vs https://github.com/elementary/mvp/blob/master/docs/human-interface-guidelines.md

**Comment by btkostner** [comment]
I realize they resolve in GitHub to the files they are pointing to, but they will break elementary docs once they get merged because we don't remove any extensions. So all of the links you added `.md` to will result in links like "[Human Interface Guidelines](https://elementary.io/docs/human-interface-guidelines.md)" and break.

**Comment by lewisgoddard** [comment]
Yes, those links are designed to work on elementary.io, where most people read them, not on github.com

**Comment by inad9300** [comment]
To the light of these responses, at least for the time being, please merge my changes but those related with "fixing" links.

**Comment by btkostner** [comment]
It would be easier for you to change those changes back in your branch. Otherwise we can change them but it involves cloning your branch, doing the changes, and creating a new PR.

**Comment by btkostner** [comment]
Also we use the `cmake` folder instead of `cmake-modules`.

If you don't get to fixing those today no big deal, I'll fix it tomorrow.

**Comment by btkostner** [comment]
@inad9300 Thank you for your help on our documentation! All the applicable changes were merged in #1302

**Comment by inad9300** [comment]
I saw you already took only the relevant changes. I was about to do it today, but thanks!

About the `cmake-modules` thing, I wrote what worked for me. I think this has a lot to do with the line that says `bzr branch lp:~elementary-os/+junk/cmake-modules`. So, if you follow the tutorial, `cmake` alone won't work.

By the way, I'm not familiarized with Vala (hopefully yet) nor its documentation, but the links pointing to there are pretty much all broken. (Perhaps is worth it opening another issue for that, right?)

**Comment by lewisgoddard** [comment]
Links to valadoc should point to valadoc.elementary.io so we can send them wherever we want.

**Comment by btkostner** [comment]
Right now, due to the way valadocs work, we are unable to link directly to a page because it all redirects to it's homepage. There is however a PR already submitted to fix the issue, we are just waiting for it to be accepted. https://github.com/flobrosch/valadoc-org/pull/65

**Comment by btkostner** [comment]
Alright, I see what you are talking about with the `cmake` issue. Luckily for the Loki release we are moving away from a bzr repo to a full package that will be installed with `sudo apt install cmake-elementary`. This should fix the confusion in that section.

**Pull request closed without merging**
