### PR TITLE
Change <button> tag to <a> tag

### PR DESCRIPTION
**Pull request by KeitIG**

### CODE REVIEW

**Comment by cassidyjames** [comment]
Hey @KeitIG, sorry that this was superseded by master with out templating system.

**Comment by cassidyjames** [comment]
I ended up adding most of the styles for the 404 page, though, so it should be an easy update. :)

**Comment by KeitIG** [comment]
@cassidyjames How is it now ?

**Comment by cassidyjames** [comment]
@KeitIG it's not a clean merge at all :-/ Could you rebase off of master then make the couple of changes? Right now it's showing the changes from an old version of master which gets messy.

**Comment by danrabbit** [comment]
I believe we decided not to do this since we would be changing it back to a button anyways for Fabian's stripe branch?

**Comment by KeitIG** [comment]
Let's close this branch.

As @danrabbit said, I propose we forget that until Fabian finishes its work. We'll see that later if it's still needed.

**Pull request closed without merging**
