### PR TITLE
Changed links in support page to StackExchange

### PR DESCRIPTION
**Pull request by shockry**
This was intended as a fix for the bitesize issue #732

### CODE REVIEW

**Comment by danrabbit** [comment]
Some of these are incorrect. The names of the tags on StackExchange aren't exactly what the LP project names are.

snap-elementary -> snap
pantheon-files -> files
pantheon-photos -> photos
switchboard -> settings
audience -> videos

It's worth noting that currently some of these tags have no associated questions

**Comment by fabianthoma** [comment]
Something I also noticed was that you are linking to `http`, how about linking to `https` by default?

**Comment by shockry** [comment]
My bad, it's my first contribution ever, now for me to be clear, the tags with no questions are ok to the change, right?

**Comment by lewisgoddard** [comment]
I think we'd be okay to linking to empty space for now, seeing as they will likely be filled later.

**Comment by fabianthoma** [comment]
@shockry Looking good to me, this is a great first pull request. Also no worries, we double check everyones work, and most of the time there are improvements to be made :wink:

**Pull request merged**
