### PR TITLE
check html for open and close tags

### LINKED ISSUE #1113: Docs - HIG - Formatting issue on German translation
### Expected behavior

No scrollbar in the document at all.

### Actual behavior

The document has a scrollbar though the browser provides a scrollbar by itself.
(Funny behaviour on a webpage about UI design ;-) )

And: it is not working at all, since it can be scrolled up and down itself by the browser scrollbar and it behaves as if the content is smaller than the screen and does not allow scrolling.

Scrolling through the page up and down keys is prevented, though the whole documentation is in one page.

### Steps to reproduce the behavior

1. Goto [https://elementary.io/de/docs/human-interface-guidelines#human-interface-guidelines](https://elementary.io/de/docs/human-interface-guidelines#human-interface-guidelines)

### System information

- **Operating system**: Ubuntu Linux
- **Operating system version**:  14.04
- **Browser**:  Firefox
- **Browser version**: 45.0.1 
- **Browser**:  Chrome
- **Browser version**: 50.0.
- **Browser**:  Vivaldi
- **Browser version**: 1.0

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1113

### Changes Summary

Adds tidy to check translation strings. It did not catch #1113, but it did find some other non-valid html tags. It's still a work in progress, but it's better than where it was.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Have these translations been changed at their source?
If they have, maybe an update is in order.

**Comment by btkostner** [comment]
they have not been changed on transifex yet

**Comment by btkostner** [comment]
So the latest comment removes tidy because it wasn't doing what I wanted very well. It instead uses regex to check that each html tag has an open and a close. It also cleans up the output making it easier to read and fix.

**Comment by lewisgoddard** [comment]
These checks are failing because of bad translations, but are we saying they are outside of the scope of this PR?

**Comment by btkostner** [comment]
Nope. I just wanted someone to check that the script is working as intended then I was planning on changing it all in transifex and pull the changes for this PR.

**Comment by lewisgoddard** [comment]
```
Checked 1540 translation files
1439 valid translation files
101 invalid translation files
```

**Comment by lewisgoddard** [comment]
See http://jenkins.elementaryos.org/job/mvp/1118/console for errors list, `/docs/learning-the-basics` line 15 seems to be a hotspot.

**Pull request merged**
