### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by emersion**
Since the `teams` branch are not ready, this adds the MIT license.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
That has a link to the teams page in it as a list of contributors. That will need changing to https://github.com/elementary/mvp/graphs/contributors

**Comment by emersion** [comment]
Fixed :-P

**Comment by lewisgoddard** [comment]
Okay, legality time:

Technically, all the code before now has remained the property of the author. They have expressly granted us license to use it, but not necessarily to sub-license it with MIT/GPL/etc.

Do we:

a) The Lawyer Way: Contact each author and get express consent from each of them, replacing any code where the request is declined.
b) The YouTube Way: Assume licensing is allowed until a complaint is filed directly with us.

**Comment by seanballais** [comment]
I prefer the YouTube Way since the author is responsible for his/her code.

**Pull request merged**
