### PR TITLE
Fix #955

### LINKED ISSUE #955: Remove The Big Lebowski reference in the HIG
Look I get it. I've watched the movie and find the (full) quote hilarious. It's great at getting the point across in *English*. However, I really think this should be removed for the following reasons:

- Translations; it's not that practical to really translate or link to IMDB with this string.
- It uses cultural specific references that only make sense to North Americans or Europeans which violates the HIG.
- The complete quote is a bit NSFW. I'm not a fan of the SJW crowd, but the full quote does violate the community code of conduct.

### PR DESCRIPTION
**Pull request by Pioneer11X**
Fixes #955

### Changes Summary

- Changed the documentation as per @danrabbit suggestions.
- Need to add a Translators note.

This pull request [ is not ] ready for review.

### CODE REVIEW

**Comment by fabianthoma** [comment]
test this please

**Comment by lewisgoddard** [comment]
@danrabbit I'm not sure if we can add translation notes, and this seems to be being translated correctly anyway (losing its pop-culture reference)

**Comment by lewisgoddard** [comment]
ok to test

**Comment by btkostner** [comment]
If you want to update this branch, I would be happy to merge it.

**Comment by Pioneer11X** [comment]
@btkostner sure.

**Pull request merged**
