### PR TITLE
Adds filesize script

### LINKED ISSUE #60: Set file size programmatically
So that we don't have to modify this page every time the iso changes (creating potential for human error), we should be setting the file size of the ISO programmatically.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7658599-set-file-size-programmatically?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by emersion**
Fixes #60.

Probably needs a cronjob or something.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
What file does this get the size for? The latest upload? That's not necessarily accurate.

Maybe it would be better to have the sourceforge and magnet links as variables in PHP, then you can dissect the 64-bit one into a more specific API call.

**Comment by emersion** [comment]
@lewisgoddard Better like this?

**Comment by lewisgoddard** [comment]
That's better, I approve your changes. Will you approve mine?

**Comment by emersion** [comment]
Yes, thanks!

**Pull request merged**
