### PR TITLE
Fix #581: Add an edit button to docs.

### LINKED ISSUE #581: Add edit links in docs
It would be really rad if there was a way to have an edit link which would show the relevant .md file in GitHub. Might encourage more edits and at the very least it would be convenient for us.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11892083-add-edit-links-in-docs?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lewisgoddard**
Fixes #581

### Changes Summary

- Add edit link.

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
screenshot from 2016-04-22 12 21 22

**Comment by btkostner** [comment]
The edit button goes over content on small sized viewports. Past that, code looks good.

does @elementary/ux approve?

**Comment by lewisgoddard** [comment]
I guess we should hide it on small viewports, along with the sidebar.

**Comment by lewisgoddard** [comment]
This was completed in #1128

**Pull request closed without merging**
