### PR TITLE
redo handler of amount selection

### LINKED ISSUE #1203: Button flashes when switching between preset and custom $ amounts.
1. Select $10
2. Select custom
3. Select $5 (this is where the $10 button flashes)
 
 
 
System information

- **Operating system**: Solus
- **Operating system version**: 1.2 
- **Browser**: Google Chrome
- **Browser version**: 51.0.2704.106 (64-bit)
- **Enabled Browser Extensions**: Tested with all of them disabled

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1203

### Changes Summary

- I redid the amount selection handler because `blur` is a horrible handler and has no way of telling what what's being focused. 
- Fixes #1203 
- Improved handling of tab only navigation for amount selectors

This pull request is ready for review: https://beta.elementary.io/branch/origin/fix-1203/

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This needs merge resolutions that I am uncertain about.

**Comment by lewisgoddard** [comment]
When I try and pay millions or billions of dollars, it doesn't validate (goes red) but passes the javascript check and lets me open the payment dialog.

**Comment by lewisgoddard** [comment]
That still seems to allow me to pay invalid amounts.

**Comment by btkostner** [comment]
are you testing locally? it seems to work locally on chrome stable, just like how it currently works

**Comment by lewisgoddard** [comment]
Nope, I guess jenkins isn't building then?

**Pull request merged**
