### PR TITLE
Section buttons look like they relate to the bug graph #324

### PR DESCRIPTION
**Pull request by pavlicekl**

### CODE REVIEW

**Comment by fabianthoma** [comment]
ok to test

**Comment by KeitIG** [comment]
@pavlicekl Check the indentation of your files.

**Comment by KeitIG** [comment]
just referencing the pr to the issue. #324

**Comment by lewisgoddard** [comment]
So this is how it looks on my screen. If I'm honest, I'm not sure that it's enough contrast, but it's probably about as much as the other section breaks are.

screenshot from 2015-11-08 00 03 34

**Comment by pavlicekl** [comment]
Maybe adding a thin 1px line above the menu section in the same color as the quote bellow would be enough to improve the contrast.

**Pull request merged**
