### PR TITLE
Fix #768

### LINKED ISSUE #768: Add sizing info to store page
This should be in smallish type on the bottom of the store page.
> All apparel is in US sizes. American Apparel sizes run a bit snug; for sizing details, see [this chart](http://www.americanapparel.net/sizing/default.asp?chart=mu.shirts).

### PR DESCRIPTION
**Pull request by lewisgoddard**
Test at http://beta.elementary.io/branch/origin/fix-768/store

### CODE REVIEW

**Comment by cassidyjames** [comment]
Good call. How about

```html
All apparel is in US sizes. Tees run a bit snug; for sizing details, see American Apparel&rsquo;s <a href="http://www.americanapparel.net/sizing/default.asp?chart=mu.shirts">sizing chart</a>.
```

**Comment by lewisgoddard** [comment]
I'm okay with that, but I've removed the `target="_blank"` since we have a script that handles that for us.

**Comment by lewisgoddard** [comment]
Do you think we should make it a `h4`, to match the top tagline. It seems to go with the "Our store currently only supports US orders.", they're similar things. 
screenshot from 2015-07-30 22 40 36

**Comment by cassidyjames** [comment]
> I've removed the target="_blank" since we have a script that handles that for us.

Eh, I'm indifferent about that. I still think it's good practice to keep the target if we know we want it popping into its own tab (and it seems weird to _rely_ on js to do that rather than keeping js as a safeguard against accidentally opening links in the same tab). I am also unsure if keeping the target in the tag affects spiders/crawlers since they won't be hitting the js and will just see the markup as-is.

**Comment by cassidyjames** [comment]
> Do you think we should make it a h4

Sure, looks good. As long as it's still below the store frame. :)

**Comment by lewisgoddard** [comment]
Actually, most spiders run JS now, so we shouldn't have any problems there. As for relying on JavaScript, I think most of our site breaks without it. You certainly can't download elementary.

**Comment by cassidyjames** [comment]
Looks good. :+1:

**Pull request merged**
