### PR TITLE
Adds navigation to docs

### LINKED ISSUE #525: Add some kind of navigation to docs [$50]
Especially with the HIG this will be necessary, but it's also kind of annoying in the code docs if you're looking for a specific section

<bountysource-plugin>
---
There is a **[$50 open bounty](https://www.bountysource.com/issues/11308871-add-some-kind-of-navigation-to-docs-25?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by emersion**
Fixes #525 

- [x] Adds breadcrumbs to docs articles and sections
- [x] Fixes sections titles (e.g. _Docs Code_ -> _Code_)
- [x] Adds custom indexes for sections (see `/docs/index.md`)

### CODE REVIEW

**Comment by lewisgoddard** [comment]
@danrabbit Do we want to use breadcrumbs like this or would you prefer a list in a block like the previous ones?

**Comment by seanballais** [comment]
@lewisgoddard Breadcrumbs can be useful.

**Comment by danrabbit** [comment]
Breadcrumbs are nice, but there's no real way right now to navigate to certain sections. For a large doc that gets annoying pretty quickly.

**Comment by seanballais** [comment]
@danrabbit I think I added a sidebar to the docs with pull request #578. There's no content yet though when you click on any of the links at the moment. I'm still figuring out how to do that though.

**Comment by emersion** [comment]
- [ ] Add a sidebar with sections links

**Comment by seanballais** [comment]
@emersion Try checking my pull request #578. What do you think?

**Comment by danrabbit** [comment]
Closing this since #588 does it better

**Comment by emersion** [comment]
Note: This PR is still useful if you want breadcrumbs.

**Pull request closed without merging**
