### PR TITLE
Fix #524 Updated Terminal Icon

### LINKED ISSUE #524: Update Terminal icon in "The Basic Setup"
It's an old one.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11308817-update-terminal-icon-in-the-basic-setup?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by yashmehrotra**
A screenshot with the new icon

screenshot from 2015-04-17 03 37 54

### CODE REVIEW

**Comment by danrabbit** [comment]
We should probably use either a 256px image scaled to 128px (So render the icon at 2x) or an SVG for HiDPI display support

**Comment by yashmehrotra** [comment]
Ok, but all the other images were 128 px so I followed that. Also I couldn't find any higher resolution image. I got the current one from [Elementary's Icon Pack.](http://bazaar.launchpad.net/~elementary-design/elementaryicons/trunk/files/head:/apps/128/)

So do you know any place where I can get a 256 px image ?

**Comment by danrabbit** [comment]
You have to export the 128px image at 256px. But honestly It would probably be better to just use the SVG.

**Comment by yashmehrotra** [comment]
So, i should just upload the 128x128 svg file instead of the png ?

**Comment by danrabbit** [comment]
Yes, that's what I would do. It would be the simplest solution

**Comment by yashmehrotra** [comment]
Ok, on it.

**Comment by yashmehrotra** [comment]
@danrabbit Kindly check the updated commit.

**Pull request merged**
