### PR TITLE
Images update

### LINKED ISSUE #810: update video icon
We released icons so we need to update to the new videos icon

### PR DESCRIPTION
**Pull request by divayprakash**
Fixes #810 

### Changes Summary

- Edited the following images -
    * `/images/notebook.png`
    * `/images/responsive-images/notebook-large.png`
    * `/images/responsive-images/notebook-medium.png`
    * `/images/responsive-images/notebook-small.png`
    * `/images/docs/learning-the-basics/dock.png`
- Compressed the images after editing

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
ok to test

**Comment by lewisgoddard** [comment]
Why does `images/docs/learning-the-basics/dock.png` look smaller and fuzzier than the original, and why doesn't it have a transparent background?

**Comment by divayprakash** [comment]
Working on it

**Comment by divayprakash** [comment]
Ping @lewisgoddard

**Comment by lewisgoddard** [comment]
ok to check

**Comment by lewisgoddard** [comment]
ok to test

**Pull request merged**
