### PR TITLE
Add receipts emails to stripe query. (fixes #340)

### LINKED ISSUE #340: Stripe not getting email address [$100]
Stripe will automatically send an email receipt upon successful payment. However, it appears Stripe isn't getting an email address from our site. When viewing transactions in the Stripe dashboard, no email addresses are listed and no receipts have been sent.

<bountysource-plugin>
---
There is a **[$100 open bounty](https://www.bountysource.com/issues/8231066-stripe-not-getting-email-address?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lewisgoddard**
Add receipts emails to stripe query.
Fixes #340.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This branch is now enabled for *[LIVE]* testing. http://beta.elementaryos.org/branch/stripe-receipts/
Cards will be charged.

**Comment by lewisgoddard** [comment]
This branch does not work, and I do not know why.

**Comment by bradaric** [comment]
Are you receiving receipts in LIVE Stripe mode? As I don't think they're sending them in test mode.

Apart from that I've noticed a couple of possible issues: [1] the catch() block after Stripe_Charge::create() was not wide enough and [2] the email passed to payment.php POST request was not encoded.

I've also had trouble with setcookie(), but that could just be a localhost problem. I'll be creating a pull request shortly.

**Comment by lewisgoddard** [comment]
If you use 127.0.0.1 instead of localhost, the cookie should set properly. Cookie standards say hostnames must have at least 1 dot in them.

**Pull request closed without merging**
