### PR TITLE
Fixes #854

### LINKED ISSUE #854: Custom Amount placeholder in Spanish website
image

The width of these input has a fixed size and hides the placeholder in spanish site

### PR DESCRIPTION
**Pull request by mrisus**
Fixes #854

### CODE REVIEW

**Comment by fabianthoma** [comment]
ok to test

**Comment by btkostner** [comment]
lgtm

**Comment by lewisgoddard** [comment]
@fabianthoma Are you aware this still hasn't been tested?

**Comment by fabianthoma** [comment]
@lewisgoddard I was not, will look into it again

**Comment by fabianthoma** [comment]
ok to test

**Comment by fabianthoma** [comment]
@lewisgoddard alright, working now

**Pull request merged**
