### PR TITLE
Allow closing of modal now that payment is recognised instantly. Fixes #341

### LINKED ISSUE #341: Download modal does not have X button, does not close on click-away or esc key
Unexpected behavior. Once the user has the download screen open, it cannot be closed without clicking a download button.

selection_003

### PR DESCRIPTION
**Pull request by lewisgoddard**
Allow closing of modal now that payment is recognised instantly.
Fixes #341
http://beta.elementaryos.org/branch/close-modal

### CODE REVIEW

**Comment by emersion** [comment]
I've got some issues with alignment and height.

selection_515

**Comment by lewisgoddard** [comment]
*sighs

Browser and Version?

**Comment by emersion** [comment]
Firefox 35.0.1 :-P

**Comment by lewisgoddard** [comment]
Doesn't do that for me. *sighs

**Comment by lewisgoddard** [comment]
@emersion Could you send me a print-screen that looks like this?

screenshot from 2015-02-11 23 30 15

**Comment by emersion** [comment]
Okay. It was my cache or something like that. Sorry :-S

**Pull request merged**
