### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by png2378**
I am concerned that after the Russian translation of many of the phrases are no longer fit in width.

### CODE REVIEW

**Comment by emersion** [comment]
No, please, no!

Change translations on Transifex, but do not edit manually files. Note that you can import translated JSON files in Transifex.

**Comment by lewisgoddard** [comment]
@emersion I was under the impression this _was_ a change from Transifex. I have opened a revert pull request that you can merge if you wish, or import this new translation in. Either way, up to you.

**Comment by png2378** [comment]
@emersion I'm sorry, I did not know about Transifex

**Comment by emersion** [comment]
@lewisgoddard No, it's okay, these translations will be overridden when pulling new translations from Transifex. That's just some useless work since it has already been done on Transifex.

@png2378 If you want to translate, please read https://github.com/elementary/mvp/blob/master/TRANSLATE.md ;-)

**Pull request merged**
