### PR TITLE
International store

### LINKED ISSUE #670: Simple International Store [$50]
We should build a super simple international sticker store.

- [x] JSON-based product list
- [x] Stripe to accept payments
- [x] International address form
- [x] Send data to payment@elementary.io

We can then manage this all on our (@maffity's and my) end. I mention stickers-only because they don't require customs forms or shipping provider integrations whereas tees would.

<bountysource-plugin>
---
There is a **[$50 open bounty](https://www.bountysource.com/issues/15291218-simple-international-store?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cassidyjames**
Still in-progress. Will fix #670.

### CODE REVIEW

**Comment by KeitIG** [comment]
:+1: 

please tell me if you need any help.

**Comment by cassidyjames** [comment]
Putting this here for later 
```json
{
  "products": [
    {
      "name": "Logomark Stickers (set of 3)",
      "sku": "sticker-logomark-set",
      "price": 1.50,
      "qty-options": [
        {
          "0": "None",
          "1": "1 set",
          "2": "2 sets",
          "3": "3 sets",
          "4": "4 sets",
          "5": "5 sets",
          "6": "6 sets",
          "7": "7 sets",
          "8": "8 sets",
          "9": "9 sets",
          "10": "10 sets"
        }
      ],
      "desc": "Set of blue 2-inch (5 cm) circle stickers with the elementary &lsquo;e&rsquo; logomark in white. Silkscreened on premium vinyl and layered with three coats of 100% UV protection meaning your stickers will stick for several years without fading.",
      "image": "http://placehold.it/600&text=Logomark Stickers"
    },
    {
      "name": "Logotype Sticker",
      "sku": "sticker-logotype",
      "price": 3.00,
      "qty-options": [
        {
          "0": "None",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4",
          "5": "5",
          "6": "6",
          "7": "7",
          "8": "8",
          "9": "9",
          "10": "10"
        }
      ],
      "desc": "elementary logotype in white on a transparent vinyl sticker; perfect for your laptop or car window. Measures approximately 8 × 2&Prime; (20 × 5 cm). Silkscreened on premium vinyl and layered with three coats of 100% UV protection meaning your stickers will stick for several years without fading.",
      "image": "http://placehold.it/600&text=Logotype Sticker"
    }
  ]
}
```

**Comment by cassidyjames** [comment]
@KeitIG I think I'm at a point where I'd want someone else to come in and do the Stripe/email stuff. :smile: There will likely be some CSS cleanup as well, but the basic page is there.

**Comment by lewisgoddard** [comment]
I'm assuming this work is still good, seeing as I can see it here: https://beta.elementary.io/branch/origin/international-store/international-store

Wondering who we need to call for Stripe stuff.

**Comment by souravsingh** [comment]
I have a waived transaction fee on the first 1000$ in revenue generated for my Stripe account.Would it work all right?

**Comment by fabianthoma** [comment]
@lewisgoddard I can hook trusted people up with our stripe details, so I guess that'd be me.

**Comment by lewisgoddard** [comment]
Is this work still valid with recent changes, or is this branch dead? It has been three months.

**Comment by lewisgoddard** [comment]
add to whitelist

**Comment by btkostner** [comment]
I haven't used any of the code here so going to assume it's dead

**Comment by lewisgoddard** [comment]
@btkostner Are you writing this feature in another, unrelated branch?

**Comment by btkostner** [comment]
should be in `new-store` branch

**Pull request closed without merging**
