### PR TITLE
Loki beta

### LINKED ISSUE #1176: Include version on home page
We should include `Freya` in the small text below the download page to prevent user confusion. Especially since a beta will be coming soon. :wink:

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #1176

### Changes Summary

- [x] Add version to homepage
- [x] Add beta hero to Developer page
- [x] Link release notes to real blog post
- [x] Update burndown chart to rc1 milestone
- [x] Hook beta download up to real ISOs

This pull request is not ready for review.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Need to revert the theme color on the developer page; should be developer purple.

**Comment by fabianthoma** [comment]
How about bumping the chart to the next milestone with this as well?

**Comment by lewisgoddard** [comment]
@snwh That's probably a good idea.

**Comment by cassidyjames** [comment]
Added to the checklist

**Pull request merged**
